(define custom-activate-default-im-name? #t)
(define custom-preserved-default-im-name 'direct)
(define default-im-name 'direct)
(define enabled-im-list '(m17n-vi-telex anthy-utf8 m17n-en-ispell))
(define enable-im-switch? #t)
(define switch-im-key '("<IgnoreCase><Alt>z" "<IgnoreCase><Shift><Control>z"))
(define switch-im-key? (make-key-predicate '("<IgnoreCase><Alt>z" "<IgnoreCase><Shift><Control>z")))
(define switch-im-skip-direct-im? #t)
(define enable-im-toggle? #t)
(define toggle-im-key '("<Super> " "<IgnoreCase><Control><Alt>c"))
(define toggle-im-key? (make-key-predicate '("<Super> " "<IgnoreCase><Control><Alt>c")))
(define toggle-im-alt-im 'direct)
(define uim-color 'uim-color-uim)
(define candidate-window-style 'table)
(define candidate-window-position 'left)
(define enable-lazy-loading? #f)
(define bridge-show-input-state? #f)
(define bridge-show-with? 'time)
(define bridge-show-input-state-time-length 3)
